config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "shibboleth" }
  localized do
    resources :budget_years
    resources :meetings
    resources :financial_requests do
      collection do
        get :not_called
      end
    end
    resources :bookings
    resources :users, except: [:new, :create]
  end

  root "welcome#index"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :financial_requests
  belongs_to :budget_year
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @meetings = Meeting.all
  end

  def show
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to @meeting, notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end

  def update
    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: 'Meeting was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @meeting.destroy
    redirect_to meetings_url, notice: 'Meeting was successfully destroyed.'
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:date, :budget_year_id)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.haml
= form_for @meeting, html: { class: "form form-horizontal meeting" } do |f|
  .form-group
    = f.label :date, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :date, class: 'form-control', required: true
    = f.error_span(:date)
  .form-group
    = f.label :budget_year_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.select :budget_year_id, options_for_select(BudgetYear.all.map{|m| [m.name, m.id]}), class: 'form-control', required: true
    = f.error_span(:budget_year_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), meetings_path, :class => 'btn btn-default'

app/views/meetings/edit.html.haml
- model_class = Meeting
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/meetings/index.html.haml
- model_class = Meeting
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:date)
      %th= model_class.human_attribute_name(:budget_year_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @meetings.each do |meeting|
      %tr
        %td= link_to meeting.id, meeting_path(meeting)
        %td= meeting.date
        %td= (meeting.budget_year ? meeting.budget_year.name : "-")
        %td=l meeting.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), meeting_path(meeting), :class => 'btn btn-default btn-xs'
          - if can?(:edit, meeting)
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_meeting_path(meeting), :class => 'btn btn-default btn-xs'
          - if can?(:destroy, meeting)
            = link_to t('.destroy', :default => t("helpers.links.destroy")), meeting_path(meeting), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- if can?(:create, Meeting)
  = link_to t('.new', :default => t("helpers.links.new")), new_meeting_path, :class => 'btn btn-primary'

app/views/meetings/new.html.haml
- model_class = Meeting
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/meetings/show.html.haml
- model_class = Meeting
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @meeting.date
%p
  %strong= model_class.human_attribute_name(:budget_year_id) + ':'
  %br
  = (@meeting.budget_year ? @meeting.budget_year.name : "-")


= link_to t('.back', :default => t("helpers.links.back")), meetings_path, :class => 'btn btn-default'
- if can?(:edit, @meeting)
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_meeting_path(@meeting), :class => 'btn btn-default'
- if can?(:destroy, @meeting)
  = link_to t('.destroy', :default => t("helpers.links.destroy")), meeting_path(@meeting), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

- if can?(:view, FinancialRequest)
  %h2=t '.financial_requests'

  %table.table.table-striped
    %thead
      %tr
        %th= FinancialRequest.human_attribute_name(:id)
        %th= FinancialRequest.human_attribute_name(:name)
        %th= FinancialRequest.human_attribute_name(:applicant)
        %th= FinancialRequest.human_attribute_name(:requested_sum)
        %th= FinancialRequest.human_attribute_name(:called_sum)
        %th= FinancialRequest.human_attribute_name(:open_sum)
        %th= FinancialRequest.human_attribute_name(:date)
        %th= FinancialRequest.human_attribute_name(:done)
        %th= FinancialRequest.human_attribute_name(:agenda_item)
        %th= FinancialRequest.human_attribute_name(:created_at)
    %tbody
      - @meeting.financial_requests.each do |financial_request|
        %tr
          %td= link_to financial_request.id, financial_request_path(financial_request)
          %td= financial_request.name
          %td= financial_request.applicant
          %td= financial_request.requested_sum
          %td= financial_request.called_sum
          %td= financial_request.open_sum
          %td= financial_request.date
          %td= financial_request.done
          %td= financial_request.agenda_item
          %td=l financial_request.created_at