config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "shibboleth" }
  localized do
    resources :budget_years
    resources :meetings
    resources :financial_requests do
      collection do
        get :not_called
      end
    end
    resources :bookings
    resources :users, except: [:new, :create]
  end

  root "welcome#index"
end

app/models/financial_request.rb
class FinancialRequest < ApplicationRecord
  belongs_to :meeting, required: false
  has_many :bookings
  monetize :requested_sum_cents, as: :requested_sum, :allow_nil => true

  def called_sum
    return bookings.map{|b| b.amount }.inject(0, :+)
  end

  def open_sum
    return 0 if done?
    return 0 if requested_sum.nil?
    return requested_sum - called_sum
  end

  def to_select_string
    name+" ("+applicant+")"
  end

  def self.remaining_sum
    FinancialRequest.all.map{|f| f.open_sum }.inject(0, :+)
  end

  def self.option_group_for_select
    option_group_helper(FinancialRequest.all)
  end

  def self.option_group_for_select_only_undone
    option_group_helper(FinancialRequest.where(done: false))
  end

  private

  def self.option_group_helper(list)
    @data = Hash.new
    list.each do |f|
      meeting = "Ohne StuKo"
      meeting = f.meeting.date unless f.meeting.nil?
      @data[meeting] ||= Array.new
      @data[meeting] << [f.to_select_string, f.id]
    end
    @data
  end
end

app/controllers/financial_requests_controller.rb
class FinancialRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_financial_request, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @financial_requests = FinancialRequest.all
  end

  def not_called
    @financial_requests = FinancialRequest.where(done: false)
    render 'index'
  end

  def show
  end

  def new
    @financial_request = FinancialRequest.new
  end

  def edit
  end

  def create
    @financial_request = FinancialRequest.new(financial_request_params)

    if @financial_request.save
      redirect_to @financial_request, notice: 'Financial Request was successfully created.'
    else
      render :new
    end
  end

  def update
    if @financial_request.update(financial_request_params)
      redirect_to @financial_request, notice: 'Financial Request was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @financial_request.destroy
    redirect_to financial_requests_url, notice: 'Financial Request was successfully destroyed'
  end

  private

  def set_financial_request
    @financial_request = FinancialRequest.find(params[:id])
  end

  def financial_request_params
    params.require(:financial_request).permit(:name, :applicant, :requested_sum, :date, :done, :agenda_item, :meeting_id)
  end
end

app/helpers/financial_requests_helper.rb
module FinancialRequestsHelper
end

app/views/financial_requests/_form.html.haml
= form_for @financial_request, html: { class: "form form-horizontal financial_request" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :applicant, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :applicant, class: 'form-control'
    = f.error_span(:applicant)
  .form-group
    = f.label :requested_sum, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :requested_sum, class: 'form-control'
    = f.error_span(:requested_sum)
  .form-group
    = f.label :date, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :date, class: 'form-control', required: true
    = f.error_span(:date)
  .form-group
    = f.label :done, class: 'control-label col-lg-2'
    .col-lg-10
      = f.check_box :done, class: 'form-control'
    = f.error_span(:done)
  .form-group
    = f.label :agenda_item, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :agenda_item, class: 'form-control'
    = f.error_span(:agenda_item)
  .form-group
    = f.label :meeting_id, class: 'control-label col-lg-2'
    .col-lg-10
      = f.select :meeting_id, options_for_select(Meeting.all.map{ |m| [m.date, m.id]}, @financial_request.meeting_id), class: 'form-control', include_blank: true
    = f.error_span(:meeting_id)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), financial_requests_path, :class => 'btn btn-default'

app/views/financial_requests/edit.html.haml
- model_class = FinancialRequest
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/financial_requests/index.html.haml
- model_class = FinancialRequest
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  - if action_name == "not_called"
    = link_to t('.all'), financial_requests_path, class: "btn btn-default"
  - else
    = link_to t('.not_called'), not_called_financial_requests_path, class: "btn btn-default"
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:applicant)
      %th= model_class.human_attribute_name(:requested_sum)
      %th= model_class.human_attribute_name(:called_sum)
      %th= model_class.human_attribute_name(:open_sum)
      %th= model_class.human_attribute_name(:date)
      %th= model_class.human_attribute_name(:done)
      %th= model_class.human_attribute_name(:agenda_item)
      %th= model_class.human_attribute_name(:meeting_id)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @financial_requests.each do |financial_request|
      %tr
        %td= link_to financial_request.id, financial_request_path(financial_request)
        %td= financial_request.name
        %td= financial_request.applicant
        %td= financial_request.requested_sum
        %td= financial_request.called_sum
        %td= financial_request.open_sum
        %td= financial_request.date
        %td= ( financial_request.done ? fa_icon("check") : fa_icon("times") )
        %td= financial_request.agenda_item
        %td= ( financial_request.meeting ? financial_request.meeting.date : "-" )
        %td
          = link_to t('.show', :default => t("helpers.links.show")), financial_request_path(financial_request), :class => 'btn btn-default btn-xs'
          - if can?(:edit, financial_request)
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_financial_request_path(financial_request), :class => 'btn btn-default btn-xs'
          - if can?(:destroy, financial_request)
            = link_to t('.destroy', :default => t("helpers.links.destroy")), financial_request_path(financial_request), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- if can?(:create, FinancialRequest)
  = link_to t('.new', :default => t("helpers.links.new")), new_financial_request_path, :class => 'btn btn-primary'

app/views/financial_requests/new.html.haml
- model_class = FinancialRequest
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/financial_requests/show.html.haml
- model_class = FinancialRequest
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @financial_request.name
%p
  %strong= model_class.human_attribute_name(:applicant) + ':'
  %br
  = @financial_request.applicant
%p
  %strong= model_class.human_attribute_name(:requested_sum) + ':'
  %br
  = @financial_request.requested_sum
%p
  %strong= model_class.human_attribute_name(:date) + ':'
  %br
  = @financial_request.date
%p
  %strong= model_class.human_attribute_name(:done) + ':'
  %br
  = @financial_request.done
%p
  %strong= model_class.human_attribute_name(:agenda_item) + ':'
  %br
  = @financial_request.agenda_item
%p
  %strong= model_class.human_attribute_name(:meeting_id) + ':'
  %br
  = @financial_request.meeting_id


= link_to t('.back', :default => t("helpers.links.back")), financial_requests_path, :class => 'btn btn-default'
- if can?(:edit, @financial_request)
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_financial_request_path(@financial_request), :class => 'btn btn-default'
- if can?(:destroy, @financial_request)
  = link_to t('.destroy', :default => t("helpers.links.destroy")), financial_request_path(@financial_request), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'


- if can?(:view, Booking)
  %h2=t '.bookings'

  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:amount)
        %th= model_class.human_attribute_name(:comment)
        %th= model_class.human_attribute_name(:date)
        %th= model_class.human_attribute_name(:budget_year_id)
        %th= model_class.human_attribute_name(:created_at)
    %tbody
      - @financial_request.bookings.each do |booking|
        %tr
          %td= link_to booking.id, booking_path(booking)
          %td= booking.amount
          %td= booking.comment
          %td= booking.date
          %td= (booking.budget_year ? booking.budget_year.name : "-")
          %td=l booking.created_at