config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "shibboleth" }
  localized do
    resources :budget_years
    resources :meetings
    resources :financial_requests do
      collection do
        get :not_called
      end
    end
    resources :bookings
    resources :users, except: [:new, :create]
  end

  root "welcome#index"
end

app/models/budget_year.rb
class BudgetYear < ApplicationRecord
  has_many :bookings
  monetize :budget_cents, as: :budget
  monetize :additional_budget_cents, as: :additional_budget

  def called_budget
    bookings.map{ |b| b.amount }.inject(0, :+)
  end

  def remaining_budget
    budget + additional_budget - (called_budget + FinancialRequest.remaining_sum)
  end
end

app/controllers/budget_years_controller.rb
class BudgetYearsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget_year, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @budget_years = BudgetYear.all
  end

  def show
  end

  def new
    @budget_year = BudgetYear.new
  end

  def edit
  end

  def create
    @budget_year = BudgetYear.new(budget_year_params)

    if @budget_year.save
      redirect_to @budget_year, notice: 'Budget year was successfully created.'
    else
      render :new
    end
  end

  def update
    if @budget_year.update(budget_year_params)
      redirect_to @budget_year, notice: 'Budget year was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @budget_year.destroy
    redirect_to budget_years_url, notice: 'Budget year  was successfully destroyed.'
  end

  private

  def set_budget_year
    @budget_year = BudgetYear.find(params[:id])
  end

  def budget_year_params
    params.require(:budget_year).permit(:name, :budget, :additional_budget)
  end

end

app/helpers/budget_years_helper.rb
module BudgetYearsHelper
end

app/views/budget_years/_form.html.haml
= form_for @budget_year, html: { class: "form form-horizontal budget_year" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :budget, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :budget, class: 'form-control', required: true
    = f.error_span(:budget)
  .form-group
    = f.label :additional_budget, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :additional_budget, class: 'form-control', required: true
    = f.error_span(:additional_budget)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), budget_years_path, :class => 'btn btn-default'

app/views/budget_years/edit.html.haml
- model_class = BudgetYear
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/budget_years/index.html.haml
- model_class = BudgetYear
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

.alert.alert-info
  Summe der blockierten Gelder:
  = FinancialRequest.remaining_sum

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:budget)
      %th= model_class.human_attribute_name(:additional_budget)
      %th= model_class.human_attribute_name(:called_budget)
      %th= model_class.human_attribute_name(:remaining_budget)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @budget_years.each do |budget_year|
      %tr
        %td= link_to budget_year.id, budget_year_path(budget_year)
        %td= budget_year.name
        %td= budget_year.budget
        %td= budget_year.additional_budget
        %td= budget_year.called_budget
        %td= budget_year.remaining_budget
        %td=l budget_year.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), budget_year_path(budget_year), :class => 'btn btn-default btn-xs'
          - if can?(:edit, budget_year)
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_budget_year_path(budget_year), :class => 'btn btn-default btn-xs'
          - if can?(:destroy, budget_year)
            = link_to t('.destroy', :default => t("helpers.links.destroy")), budget_year_path(budget_year), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- if can?(:create, BudgetYear)
  = link_to t('.new', :default => t("helpers.links.new")), new_budget_year_path, :class => 'btn btn-primary'

app/views/budget_years/new.html.haml
- model_class = BudgetYear
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/budget_years/show.html.haml
- model_class = BudgetYear
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @budget_year.name
%p
  %strong= model_class.human_attribute_name(:budget) + ':'
  %br
  = @budget_year.budget
%p
  %strong= model_class.human_attribute_name(:additional_budget) + ':'
  %br
  = @budget_year.additional_budget


= link_to t('.back', :default => t("helpers.links.back")), budget_years_path, :class => 'btn btn-default'
- if can?(:edit, @budget_year)
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_budget_year_path(@budget_year), :class => 'btn btn-default'
- if can?(:destroy, @budget_year)
  = link_to t('.destroy', :default => t("helpers.links.destroy")), budget_year_path(@budget_year), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'