config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "shibboleth" }
  localized do
    resources :budget_years
    resources :meetings
    resources :financial_requests do
      collection do
        get :not_called
      end
    end
    resources :bookings
    resources :users, except: [:new, :create]
  end

  root "welcome#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.nil?
      cannot :manage, :all
    elsif user.role == "admin"
      can :manage, :all
      cannot :destroy, User, id: user.id
    elsif user.role == "stugenbeauftragter"
      can :manage, :all
      cannot :manage, User
    elsif user.role == "financial_administration"
      can :read, :all
      cannot :read, User
      can :manage, Booking
      can :not_called, FinancialRequest
    else
      can :read, BudgetYear
      can :read, FinancialRequest
      can :not_called, FinancialRequest
      can :read, Meeting
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :budget_year
  belongs_to :financial_request

  monetize :amount_cents, as: :amount
end

app/models/budget_year.rb
class BudgetYear < ApplicationRecord
  has_many :bookings
  monetize :budget_cents, as: :budget
  monetize :additional_budget_cents, as: :additional_budget

  def called_budget
    bookings.map{ |b| b.amount }.inject(0, :+)
  end

  def remaining_budget
    budget + additional_budget - (called_budget + FinancialRequest.remaining_sum)
  end
end

app/models/financial_request.rb
class FinancialRequest < ApplicationRecord
  belongs_to :meeting, required: false
  has_many :bookings
  monetize :requested_sum_cents, as: :requested_sum, :allow_nil => true

  def called_sum
    return bookings.map{|b| b.amount }.inject(0, :+)
  end

  def open_sum
    return 0 if done?
    return 0 if requested_sum.nil?
    return requested_sum - called_sum
  end

  def to_select_string
    name+" ("+applicant+")"
  end

  def self.remaining_sum
    FinancialRequest.all.map{|f| f.open_sum }.inject(0, :+)
  end

  def self.option_group_for_select
    option_group_helper(FinancialRequest.all)
  end

  def self.option_group_for_select_only_undone
    option_group_helper(FinancialRequest.where(done: false))
  end

  private

  def self.option_group_helper(list)
    @data = Hash.new
    list.each do |f|
      meeting = "Ohne StuKo"
      meeting = f.meeting.date unless f.meeting.nil?
      @data[meeting] ||= Array.new
      @data[meeting] << [f.to_select_string, f.id]
    end
    @data
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :financial_requests
  belongs_to :budget_year
end

app/models/user.rb
class User < ApplicationRecord
  devise :trackable, :omniauthable, :omniauth_providers => [:shibboleth]

  def update_data(auth)
  end

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
#  before_action :development_sign_in

  rescue_from CanCan::AccessDenied do |exception|
    if can? :read, exception.subject
      redirect_to exception.subject, :alert => exception.message
    else
      redirect_to root_url, :alert => exception.message
    end
  end

  private

  def development_sign_in
    sign_in User.first if Rails.env.development?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @bookings = Booking.all.order(:date)
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:amount, :comment, :date, :budget_year_id, :financial_request_id)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @meetings = Meeting.all
  end

  def show
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to @meeting, notice: 'Meeting was successfully created.'
    else
      render :new
    end
  end

  def update
    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: 'Meeting was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @meeting.destroy
    redirect_to meetings_url, notice: 'Meeting was successfully destroyed.'
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:date, :budget_year_id)
  end
end

app/controllers/shibboleth_controller.rb
class ShibbolethController < Devise::OmniauthCallbacksController
    def shibboleth
        @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
            @user.update_data(request.env["omniauth.auth"])
            sign_in @user
            redirect_to root_path
        else
            @user.save
            @user.update_data(request.env["omniauth.auth"])
            sign_in @user
            session["devise.shibboleth_data"] = request.env["omniauth.auth"]
            redirect_to root_path
        end
    end

    def failure
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to budget_years_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/budget_years_helper.rb
module BudgetYearsHelper
end

app/helpers/financial_requests_helper.rb
module FinancialRequestsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "StukoFinanzen"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72', skip_pipeline: true
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', skip_pipeline: true
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon', skip_pipeline: true
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") StukoFinanzen
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to t('budget_years.index.title'), budget_years_path
            %li= link_to t('meetings.index.title'), meetings_path
            %li= link_to t('financial_requests.index.title'), financial_requests_path
            - if can? :read, Booking
              %li= link_to t('bookings.index.title'), bookings_path
            - if can? :read, User
              %li= link_to t('users.index.title'), users_path

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      %footer
        %p &copy; Jan-Frederik Rieckers 2017